### ISSUE TITLE
version 0.0.3 fails on ADB

### ISSUE THREAD

**Issue by kadel** [projectatomic/openshift2nulecule#21]
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"")
```

It look like that it is because older `python-docker-py` library :-(

**Comment by LalatenduMohanty** [comment]
@kadel What is the minimum python-docker-py version we need. We should update the spec file accordingly.
Also while testing on ADB ,  which python-docker-py version you have used?

**Comment by kadel** [comment]
@LalatenduMohanty I screw up this one big time :-( 
I tested it on box where I had installed docker-py from pip, and I forgot about it :-(
It looks like it requires dokcer-py version 1.6.0  and up.

It seems that '<1.6.0' doesn't support pulling with digest like this: `image@sha256:ecdc5effb4032c0b8c5af28040b059991945916f7ec60d8ebb7f671212373027`

**Comment by LalatenduMohanty** [comment]
@kadel I will build 1.7.0  in http://buildlogs.centos.org/centos/7/atomic/x86_64/adb/

**Comment by kadel** [comment]
If found couple more issues. I'll have to release new version to fix them.

**Comment by kadel** [comment]
I'm going to release 0.0.4 with small fixes - #23.
But before that I'm going to test it properly on clean box ;-)

**Comment by kadel** [comment]
@LalatenduMohanty 
https://github.com/projectatomic/openshift2nulecule/releases/tag/v0.0.4
I updated spec. now it requires python-docker-py >= 1.6.0

I tested this with testing repo (http://buildlogs.centos.org/centos/7/atomic/x86_64/adb/) and it fails on `python-docker-py` as expected
```
--> Finished Dependency Resolution
Error: Package: openshift2nulecule-0.0.4-1.el7.centos.noarch (tkral-openshift2nulecle)
           Requires: python-docker-py >= 1.6.0
           Installed: python-docker-py-1.4.0-118.el7.noarch (@koji-override-0)
               python-docker-py = 1.4.0-118.el7
           Available: docker-python-1.4.0-115.el7.x86_64 (extras)
               python-docker-py = 1.4.0-115.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

To test this I've done horrible thing and installed newer version of `python-docker-py` from Fedora to ADB.
```yum install https://kojipkgs.fedoraproject.org//packages/python-docker-py/1.6.0/1.fc23/noarch/python-docker-py-1.6.0-1.fc23.noarch.rpm```

With newer version of docker-py library everything seems to work fine.

**Comment by LalatenduMohanty** [comment]
@kadel python-docker-py needs  python-mock ;)

**Comment by kadel** [comment]
ajaj packages are starting to add up

**Comment by LalatenduMohanty** [comment]
@kadel the issue is, if just adding one RPM increases the Vagrantbox size considerably then we have to rethink how we want to deliver it.

**Comment by LalatenduMohanty** [comment]
python-mock needs python-unittest2

**Comment by kadel** [comment]
@LalatenduMohanty hmm :-( And it looks like just python-mock wont be enough :-(
there is also: python-pytest-cov and python-flake8

**Comment by LalatenduMohanty** [comment]
> python-mock needs python-unittest2

python-unittest2 needs python-traceback2 ->   python-traceback2  need python-pbr

Am I doing something wrong here? @kadel as you mentioned python-pytest-cov and python-flake8 , but I am seeing some other dependencies.

**Comment by kadel** [comment]
@LalatenduMohanty I saw python-flake8 and python-pytest-cov here https://github.com/docker/docker-py/blob/master/test-requirements.txt  and also as BuildRequires in Fedora package.

**Comment by praveenkumar** [comment]
@LalatenduMohanty @kadel as per dnf on fedora-23 I checked `docker-py` depend on some standard packages only which I hope is already present (hope repoquery listed correct dependency). 

```
$ sudo dnf repoquery --requires --resolve python-docker-py
Last metadata expiration check performed 0:14:42 ago on Fri Mar  4 15:36:50 2016.
python-0:2.7.10-8.fc23.i686
python-0:2.7.10-8.fc23.x86_64
python-requests-0:2.9.1-1.fc23.noarch
python-six-0:1.9.0-3.fc23.noarch
python-websocket-client-0:0.32.0-1.fc23.noarch
```

**Comment by kadel** [comment]
openshift2nulecule doesn't use docker-py anymore
