### ISSUE TITLE
Add option  to specify Atomic App version

### ISSUE THREAD

**Issue by kadel** [projectatomic/openshift2nulecule#26]
Right now  version of Atomic App that is in Dockerfile is based on `ATOMICAPP_VERSION` constant.

It would be nice to have possibility to override this using command line parameter.

**Comment by surajssd** [comment]
@kadel can you elaborate on the use-case?

**Comment by kadel** [comment]
When new version of Atomic app is released we have to update `ATOMICAPP_VERSION` constant and release new version.  Otherwise all exported apps are going to use old atomic app version and we  don't want that.

**Comment by surajssd** [comment]
@kadel it is a good optional right? I am working on it BTW!
