### ISSUE TITLE
Do not export the artifacts from Openshift using "all"

### ISSUE THREAD

**Issue by surajssd** [projectatomic/openshift2nulecule#33]
While exporting the artifacts from Openshift do not use `oc export all` this can cause problems while importing it into other implementation of Openshift.

**Comment by surajssd** [comment]
What I think from the [email response](https://lists.openshift.redhat.com/openshift-archives/dev/2016-March/msg00035.html) we can export only `svc,dc,bc,is,route` and it can sufficiently migrate the application from one OS instance to other.

**Comment by surajssd** [comment]
@kadel what do you think?

**Comment by surajssd** [comment]
@kadel I tried exporting only `svc,dc,bc,is,route` objects and I could successfully import into other openshift instance (But the building has to be performed on other host of the application).

**Comment by kadel** [comment]
We can try to do this,  but I'm afraid that this might not be enough :-( 
I tried raise my concerns about this here: https://lists.openshift.redhat.com/openshift-archives/dev/2016-March/msg00042.html

**Comment by surajssd** [comment]
Yes read your response, lets see what is best to do!

**Comment by kadel** [comment]
I think we have to try this, or we are never going to figure this out :-(

**Comment by surajssd** [comment]
@kadel okay I will send a PR for this!

**Comment by kadel** [comment]
So far nobody was able to tell me if it is good or bad idea.

But I think that we should try solve this by exporting `all` and that only picking objects that we need.
We can try to use info from annotations to decide what to keep and that filter out.

**Comment by kadel** [comment]
For example I can see that ReplicationController that is generated by
DeploymentConfig has annotation 'openshift.io/deployment-config.name:
...' and same apply for its Pods.

For Pod that was created by ReplicationController (that is not from
DeploymentConfig) I see annotation 'kubernetes.io/created-by: ...'

**Comment by kadel** [comment]
@surajssd Can you please update README or create docs about this?
It would be nice to describe what what is exported and what is not exported.

**Comment by surajssd** [comment]
@kadel yep will do that

**Comment by surajssd** [comment]
@kadel PR #45

**Comment by kadel** [comment]
with #48 we are now exporting everything except pods, this should work for most apps.
I'm closing. We can create new issue when we find something that is not working
