### ISSUE TITLE
We shouldn't export whole project

### ISSUE THREAD

**Issue by kadel** [projectatomic/openshift2nulecule#40]
Right now we assume that project=application, in most cases that is not true and one project may contain more application. 
We need to figure out way how to select and export only part of project that is one application (probably using labels)

**Comment by surajssd** [comment]
I think we also need an option for `--app`?

**Comment by kadel** [comment]
At first we probably need to define what actually one app is (where are app boundaries) :-)

**Comment by surajssd** [comment]
Yes I just added the comment so as to document the idea!! :)

**Comment by surajssd** [comment]
@kadel I found that the artifacts for specific app have name starting with its name

```bash
[vagrant@centos7-adb ~]$ oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-hello-world.git
--> Found Docker image 1be589e (8 hours old) from Docker Hub for "centos/ruby-22-centos7"
    * An image stream will be created as "ruby-22-centos7:latest" that will track the source image
    * A source build using source code from https://github.com/openshift/ruby-hello-world.git will be created
      * The resulting image will be pushed to image stream "ruby-hello-world:latest"
      * Every time "ruby-22-centos7:latest" changes a new build will be triggered
    * This image will be deployed in deployment config "ruby-hello-world"
    * Port 8080/tcp will be load balanced by service "ruby-hello-world"
--> Creating resources with label app=ruby-hello-world ...
    ImageStream "ruby-22-centos7" created
    ImageStream "ruby-hello-world" created
    BuildConfig "ruby-hello-world" created
    DeploymentConfig "ruby-hello-world" created
    Service "ruby-hello-world" created
--> Success
    Build scheduled for "ruby-hello-world" - use the logs command to track its progress.
    Run 'oc status' to view your app.
[vagrant@centos7-adb ~]$ oc new-app https://github.com/openshift/nodejs-ex -l name=myapp
--> Found image 92eee82 (2 weeks old) in image stream "nodejs in project openshift" under tag :latest for "nodejs"
    * The source repository appears to match: nodejs
    * A source build using source code from https://github.com/openshift/nodejs-ex will be created
      * The resulting image will be pushed to image stream "nodejs-ex:latest"
    * This image will be deployed in deployment config "nodejs-ex"
    * Port 8080/tcp will be load balanced by service "nodejs-ex"
--> Creating resources with label name=myapp ...
    ImageStream "nodejs-ex" created
    BuildConfig "nodejs-ex" created
    DeploymentConfig "nodejs-ex" created
    Service "nodejs-ex" created
--> Success
    Build scheduled for "nodejs-ex" - use the logs command to track its progress.
    Run 'oc status' to view your app.
[vagrant@centos7-adb ~]$ 


(atomic) ✔ ~/openshift2nulecule [master ↑·56|✔] 
05:43 $ openshift2nulecule --project multiple-apps --output ~/exported/wholeproject
INFO - Nulecule application created in /home/vagrant/exported/wholeproject

    
[vagrant@centos7-adb wholeproject]$ ll
total 8
drwxrwxr-x. 4 vagrant vagrant  39 Mar 22 05:44 artifacts
-rw-rw-r--. 1 vagrant vagrant 245 Mar 22 05:44 Dockerfile
-rw-rw-r--. 1 vagrant vagrant 839 Mar 22 05:44 Nulecule
[vagrant@centos7-adb wholeproject]$ vi artifacts/openshift/
nodejs-ex-BuildConfig.json              nodejs-ex-Service.json                  ruby-hello-world-DeploymentConfig.json  
nodejs-ex-DeploymentConfig.json         ruby-22-centos7-ImageStream.json        ruby-hello-world-ImageStream.json       
nodejs-ex-ImageStream.json              ruby-hello-world-BuildConfig.json       ruby-hello-world-Service.json           
[vagrant@centos7-adb wholeproject]$ 

```

**Comment by kadel** [comment]
I'm not sure if same applies for all applications :-(

**Comment by surajssd** [comment]
@kadel What are situations that can happen? I mean when I deploy the app via web console I have to provide the name of the App (that's a mandatory field), and when I deploy using commandline using `oc` when I deploy using git then it takes over the project name. When I deploy using container it takes over the name of the container, what is the usecase I am missing?

**Comment by kadel** [comment]
When you write your create objects using `oc create -f `.

**Comment by kadel** [comment]
But those are cases that we can not reasonably cover :-(

You are right we can add `--app` argument, or maybe little bit generic option, something like `--label-selector`. So you could use `--label-selector app=myapp` or any other label.

**Comment by kadel** [comment]
I just found that we definitely should not really on `app` label. I tried nodejs quickstart example that is part of the OpenShift and there is no app label. Instead of this there is `name`

**Comment by surajssd** [comment]
or something like `app-selector name=myapp` ? `label-selector` is little confusing or somebody who has not written any Kubernetes or OpenShift conf cannot understand! 

You mentioned about making it generic what other will `label-selector` do in this context?

**Comment by kadel** [comment]
> or something like app-selector name=myapp ? label-selector is little confusing or somebody who has not written any Kubernetes or OpenShift conf cannot understand!

`oc` and `kubectl` are using `--selector` (or short `-l`) for filtering object by labels.
I think that we should use same mechanism, and if possible even use same option name.
 
> You mentioned about making it generic what other will label-selector do in this context?
by generic I meant that it should be able to select by any label, not just app

**Comment by surajssd** [comment]
okay cool we can go that way!! :) I will start working on it then.
