### ISSUE TITLE
Export/Import not working probably due to image streams

### ISSUE THREAD

**Issue by tnozicka** [projectatomic/openshift2nulecule#56]
I tried exporting a project and importing it back to the same openshift cluster, but it does not work. (It was exported and imported without images.)

It was a simple app: https://github.com/openshift/ruby-hello-world

After importing it back to openshift it won't produce build. The reason are 2 image streams:
 1) ruby-22-centos7 - is missing tags

```
Name: ruby-22-centos7
Docker Pull Spec: 172.30.131.143:5000/original-project/ruby-22-centos7
Tags: <none>
```

 2) ruby-hello-world - has a tag with to the old registry and does not have permissions to pull 

```
Name: ruby-hello-world
Docker Pull Spec: 172.30.131.143:5000/original-project/ruby-hello-world
Tag Spec                                Created PullSpec    Image
latest  172.30.131.143:5000/original-project/ruby-hello-world:latest        <not available> <not available>
```

**Errors**:
- On openshift web page click on button "Start build":

```
An error occurred while starting the build.imageStreamTag "ruby-22-centos7:latest" not found
```
- In events:

```
Back-off pulling image "172.30.131.143:5000/original-project/ruby-hello-world...
```

**Comment by kadel** [comment]
I found this:  https://github.com/projectatomic/openshift2nulecule/issues/42#issuecomment-199896872
where I'm describing how it worked last week :-( I still don't know what changed, that it is not working anymore :-(

**Comment by surajssd** [comment]
@tnozicka are you trying this on the new ADB 1.7.2?

**Comment by tnozicka** [comment]
@surajssd I tried it on ADB 1.7.1, 1.7.2 and @kadel tried it with the same result as well.

**Comment by kadel** [comment]
after more investigation @tnozicka  reported this as issue in Origin https://github.com/openshift/origin/issues/8327 More info about this problem is at that issue

**Comment by kadel** [comment]
For now I implemented ugly workaround (remove annotations from all images streams). #56

**Comment by tnozicka** [comment]
closing due to age
