### ISSUE TITLE
add openshift

### ISSUE THREAD

**Issue by kadel** [projectatomic/openshift2nulecule#6]
exported Nulecule should include both kubernetes and openshift artifacts

**Comment by surajssd** [comment]
Will look into this.

**Comment by kadel** [comment]
:+1: 
I've few more notes for this. This is going to need little bit more research to this right.
For Openshift we need to export more objects than we currently doing for Kubernetes. We should also export DeploymentConfigs, probably also BuildConfigs, Templates and others.

**Comment by surajssd** [comment]
So why not do 
`oc --namespace som-random-project export all` in the export function and then pick things that we need!!

**Comment by surajssd** [comment]
For this particular feature we can export `replicationController` and `service` and then if imported into other machine it works, I tried doing it.

On one machine I did:

```bash
[vagrant@centos7-adb ~]$ oc --namespace hello export rc  > rc
[vagrant@centos7-adb ~]$ oc --namespace hello export svc > svc
```


Copied those files in other machine
```bash
[vagrant@centos7-adb ~]$ oc create -f rc.yaml 

replicationcontroller "nginx-1" created
[vagrant@centos7-adb ~]$ oc create -f svc.yaml 
service "nginx" created
[vagrant@centos7-adb ~]$ 
```

**Comment by kadel** [comment]
> So why not do
oc --namespace som-random-project export all in the export function and then pick things that we need!! If we start doing this then issue #10 becomes invalid.

For artifacts for OpenShift provider we can do this. And we **probably** should, so we don't loose any information.

**Comment by surajssd** [comment]
@kadel yes sure

**Comment by surajssd** [comment]
@kadel so should this be closed?

**Comment by kadel** [comment]
@surajssd Yes, you can close this :wink:

**Comment by surajssd** [comment]
@kadel closing :+1: :)
